<div   class="col-md-3 col-xs-6 col-sm-6 clo-lg-3 ">
		<div class="indeximg">
			<div class="view"></div>
			<a href='[field:arcurl/]'>[field:image/]</a>

			<p><a href="[field:arcurl/]">[field:title/]</a></p>
			<small style="color: #c0c0c0"><img src="/templets/funboo/images/type.png" style="width:11px;">[field:typelink/]<img src="/templets/funboo/images/view.png" style="width:16px;">[field:click/]hits</small>
		</div>

	</div>