<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",87,241);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",313,328);
$z[2]=Array("title","",344,429);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",453,470);
$z[4]=Array("click","",515,529);

?>