<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",87,241);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",312,327);
$z[2]=Array("title","",343,428);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",452,469);
$z[4]=Array("pubdate","",508,554);
$z[4][4]['function']="GetDateTimeMK(@me)";

?>