
<field:names itemname="贵姓" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:names>

<field:mobile itemname="手机号码" autofield="1" type="int" isnull="true" default=""  maxlength="11" page="">
</field:mobile>

<field:type itemname="需求类型" autofield="1" type="select" isnull="true" default="网站建设,小程序开发,视频创作,平面设计"  maxlength="250" page="">
</field:type>

<field:baojia itemname="需求报价" autofield="1" type="select" isnull="true" default="5000以下,10000以下,50000以下,其他价格"  maxlength="250" page="">
</field:baojia>
