<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'>\r\n      <figure><img src='{@me['litpic']}'/></figure></a>\"); ",82,261);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",333,348);
$z[2]=Array("title","",364,449);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",561,578);
$z[4]=Array("click","",660,674);

?>