<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",83,237);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",308,323);
$z[2]=Array("title","",339,424);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",448,465);
$z[4]=Array("pubdate","",504,550);
$z[4][4]['function']="GetDateTimeMK(@me)";

?>