<div class="col-md-4 col-lg-4 col-sm-6 col-xs-6">
		<div class="newbox">
			<a href='[field:arcurl/]'><div class="newbox-l" style="background:url([field:image/])no-repeat center / cover;">
				
			</div></a>
			<div class="newbox-r">
				<h2><a href="[field:arcurl/]">[field:title/]</a></h2>
				<p>这是一个牛逼的描述可以是很长的很长的，比牛鞭还长很多呢！这是一个牛逼的描述可以是很长的很长的，比牛鞭还长很多呢！这是一个牛逼的描述可以是很长的很长的，比牛鞭还长很多呢！</p>
			</div>
		</div>
	</div>