<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",91,245);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",321,336);
$z[2]=Array("title","",352,437);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",463,480);
$z[4]=Array("click","",525,539);

?>