<li class="container" style="background-color: white;height: 100%; margin-bottom:5px;margin-left: -10px;margin-right: -10px;">
            <div class="col-xs-4 col-sm-4 col-md-54 col-lg-54" style="padding: 15px 0px 15px 0px"> <a href="[field:arcurl/]">[field:image/]</a>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8" style="padding: 15px 0px 15px 15px;">
               <h4 style="font-weight: bold;line-height: 0;"><a href="[field:arcurl/]">[field:title/]</a></h4>
               <p style="color: #8d8d8d;">[field:source/]</p>
              <div class="am-list-item-text"><p><span style="font-weight: bold;font-size: 14px; color: #ff4777;">[field:shorttitle/]</span>元<i class="right" style="float: right;padding-right: 15px;">已报名[field:click/]人</i></p></div>

             <!--  <a href="/plus/stow.php?aid=[field:id/]">收藏</a> -->
            
          </li>