<?php
$z[0]=Array("arcurl","",104,119);
$z[1]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'>\r\n            <img class=\"img-responsive\" src='{@me['litpic']}'/></a>\r\n            <div class=\"caption \">\r\n              <h3 style=\"color:#999999;\">\r\n                [field:title",151,435);
$z[1][4]['runphp']="yes";
$z[2]=Array("typelink","",518,535);
$z[3]=Array("pubdate","",536,582);
$z[3][4]['function']="GetDateTimeMK(@me)";

?>