<?php
$z[0]=Array("channelartlist","\r\n		<div class=\"swiper-slide\">\r\n			<div class=\"swiper-slide-box\">\r\n			{dede:type}\r\n			<h1>[field:typename/]</h1>\r\n			<h5>[field:description/]</h5>\r\n			{/dede:type}\r\n			<!-- 子栏目 -->\r\n			<ul class=\"list-group\">\r\n				{dede:channel type='son'}\r\n				<li class=\"list-group-item\"><a href='[field:typelink /]'>[field:typename/]</a></li>\r\n				{/dede:channel}\r\n			</ul>\r\n			</div>\r\n		</div>\r\n		",92,537);
$z[0][4]['typeid']="20";

?>