<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
      <div class="caption">
        <h3><a href="[field:arcurl/]" class="title">[field:title/]</a></h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>