<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",83,237);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",308,323);
$z[2]=Array("title","",339,353);
$z[3]=Array("title","",353,438);
$z[3][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[4]=Array("typelink","",462,479);
$z[5]=Array("pubdate","",518,564);
$z[5][4]['function']="GetDateTimeMK(@me)";

?>