<?php
$z[0]=Array("typeurl","",37,53);
$z[1]=Array("typename","",55,72);
$z[2]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",226,380);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",451,466);
$z[4]=Array("title","",482,496);
$z[5]=Array("typelink","",520,537);
$z[6]=Array("pubdate","",576,622);
$z[6][4]['function']="GetDateTimeMK(@me)";

?>