
  <li role="presentation"><a href="[field:typeurl/]">[field:typename/]</a></li>
  
</ul>
 
<!-- 循环体 -->
{dede:list pagesize='10'}
<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="[field:arcurl/]" class="title">[field:title/]</a></h3>
      <small>[field:typelink/]</small><small style="color:#c0c0c0;">|[field:pubdate function="GetDateTimeMK(@me)"/]</small>

    </div>
  </div>
</div>
{/dede:list}

  <!-- 循环体 --> 

<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    <a href="/case/web/wz_2.html" class="preview"><img src="/uploads/allimg/171109/2_1345213041.jpg"></a>
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="/case/web/wz_2.html" class="title">动物保健品品牌网站</a></h3>
      <small><a href="/plus/list.php?tid=3">网站建设</a></small><small style="color:#c0c0c0;">|2017-11-09 13:45:44</small>

    </div>
  </div>
</div>
<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    <a href="/case/web/wz_2.html" class="preview"><img src="/uploads/allimg/171109/2_1345213041.jpg"></a>
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="/case/web/wz_2.html" class="title">动物保健品品牌网站</a></h3>
      <small><a href="/plus/list.php?tid=3">网站建设</a></small><small style="color:#c0c0c0;">|2017-11-09 13:45:44</small>

    </div>
  </div>
</div>
<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    <a href="/case/web/wz_2.html" class="preview"><img src="/uploads/allimg/171109/2_1345213041.jpg"></a>
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="/case/web/wz_2.html" class="title">动物保健品品牌网站</a></h3>
      <small><a href="/plus/list.php?tid=3">网站建设</a></small><small style="color:#c0c0c0;">|2017-11-09 13:45:44</small>

    </div>
  </div>
</div>
<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    <a href="/case/web/wz_2.html" class="preview"><img src="/uploads/allimg/171109/2_1345213041.jpg"></a>
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="/case/web/wz_2.html" class="title">动物保健品品牌网站</a></h3>
      <small><a href="/plus/list.php?tid=3">网站建设</a></small><small style="color:#c0c0c0;">|2017-11-09 13:45:44</small>

    </div>
  </div>
</div>
<div class="col-md-4 col-xs-6 col-sm-6 clo-lg-3">
  <div class="thumbnail">
    <a href="/case/web/wz_2.html" class="preview"><img src="/uploads/allimg/171109/2_1345213041.jpg"></a>
    <div class="caption">
      <h3 style="color:#c0c0c0;"><a href="/case/web/wz_2.html" class="title">动物保健品品牌网站</a></h3>
      <small><a href="/plus/list.php?tid=3">网站建设</a></small><small style="color:#c0c0c0;">|2017-11-09 13:45:44</small>

    </div>
  </div>
</div>



</div>

</div>



{dede:include filename="footer.htm"