<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'>\r\n      <figure><img src='{@me['litpic']}'/></figure></a>\"); ",81,260);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",332,347);
$z[2]=Array("title","",363,448);
$z[2][4]['function']="( strlen(\"@me\")>15 ? cn_substr(\"@me\",15).\"...\" : \"@me\" )";
$z[3]=Array("typelink","",559,576);
$z[4]=Array("click","",640,654);

?>