<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",172,189);
$z[2]=Array("arcurl","",204,219);
$z[3]=Array("title","",235,249);
$z[4]=Array("pubdate","",298,344);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",369,383);
$z[6]=Array("scores","",408,423);
$z[7]=Array("description","",458,478);

?>