<?php
$z[0]=Array("global","",420,452);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("flink"," [field:link /] ",1171,1258);
$z[1][4]['row']="24";
$z[1][4]['type']="text";
$z[1][4]['titlelen']="24";
$z[1][4]['typeid']="0";
$z[2]=Array("type","  [field:typename/]",1437,1491);
$z[2][4]['typeid']="21";
$z[3]=Array("channelartlist","\r\n\r\n					<li>{dede:field name='typename'/}</li>\r\n\r\n					",1518,1629);
$z[3][4]['typeid']="21";
$z[4]=Array("type","  [field:typename/] ",1767,1822);
$z[4][4]['typeid']="22";
$z[5]=Array("channelartlist","\r\n\r\n					<li>{dede:field name='typename'/}</li>\r\n\r\n					",1849,1960);
$z[5][4]['typeid']="22";
$z[6]=Array("type","  [field:typename/] ",2095,2150);
$z[6][4]['typeid']="23";
$z[7]=Array("channelartlist","\r\n\r\n					<li>{dede:field name='typename'/}</li>\r\n\r\n					",2177,2288);
$z[7][4]['typeid']="23";
$z[8]=Array("type","  [field:typename/] ",2410,2465);
$z[8][4]['typeid']="24";
$z[9]=Array("channelartlist","\r\n\r\n					<li>{dede:field name='typename'/}</li>\r\n\r\n					",2492,2603);
$z[9][4]['typeid']="24";
$z[10]=Array("type","  [field:typename/] ",2717,2772);
$z[10][4]['typeid']="25";
$z[11]=Array("channelartlist","\r\n\r\n					<li>{dede:field name='typename'/}</li>\r\n\r\n					",2799,2910);
$z[11][4]['typeid']="25";
$z[12]=Array("global","",4811,4843);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",4917,4949);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",5732,5764);
$z[14][4]['name']="cfg_templets_skin";
$z[15]=Array("global","",5810,5842);
$z[15][4]['name']="cfg_templets_skin";

?>