<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?>
<!-- //底部模板 -->
<div class="container-fluid hidden-xs hidden-sm" style="background: #5cb85c;height: 150px;">
 
	<div class="row-fluid" style="margin: auto;max-width: 1200px;padding-top: 35px;">



 <h2 class="text-center" style="color:white"><strong>有任何疑问，请联系我们!</strong>
<button class="btn btn-primary" type="button"  style="margin-left: 25px;">
 <img src="{dede:global.cfg_templets_skin/}/images/qq.png" width="20">QQ咨询
</button></h2>
	
	
	

	</div>
</div>
<!-- 第二段 -->
<div class="progress hidden-xs hidden-sm" style="margin-top: -150px;">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
    <span class="sr-only"></span>
  </div>
</div>

<div class="container-fluid hidden-xs hidden-sm" style="background:black;line-height:10px;height: 400px;">
	<div class="row-fluid" style="padding-top: 120px;margin: auto;max-width: 1200px;">



		<div class=" col-md-3 col-xs-12 col-sm-12 col-lg-3 hidden-xs">
		   
		   <address>
		   <strong>KEYWORDS/关键词</strong></address>
		   <address>
		   绵阳网站建设<br>
		  绵阳网站设计<br>
		   绵阳网站开发<br>
		   绵阳SE0<br>
		   绵阳网站优化
		   </address>

		
		
		
  <address>网站地图</address>



		  
		
		
		</div>

		<div class=" col-md-3 col-xs-12 col-sm-12 col-lg-3 ">
		   
		   <address>
		   <strong>SERVICE/服务项目</strong>
		   </address>
		   <address>
		   绵阳网站建设<br>
		   手机网站建设<br>
		   营销网站设计<br>
		   产品包装设计<br>
		   微信小程序开发<br>
		   
		   </address>
		   
		
		
		
		</div>
		<div class=" col-md-3 col-xs-12 col-sm-12 col-lg-3 ">
		  <address> <strong>微信小程序</strong><br>手机扫描联系我们</address>
		  
	
		  <img src="{dede:global.cfg_templets_skin/}/images/xcx.jpg" width="120" height="120">
		
		
		</div>
		<div class=" col-md-3 col-xs-12 col-sm-12 col-lg-3   hidden-sm">
		
		<address>
  <strong>方博互动</strong><br>
  Add:绵阳涪城区-得月星城<br>
  
  <abbr title="Phone">Tel</abbr> (153) 5125-3509
</address>

<address>

  <strong href="mailto:#">195446054@qq.com</strong><br>
  Copyright @ 2017 方博互动 Design All rights reserved
</address>
		  
		
		</div>

		<div class=" col-md-3 col-xs-12 col-sm-12 col-lg-3   hidden-sm">
		
		
  <address>蜀ICP备14028737-1号</address>



		  
		
		</div>
	</div>
</div>
<!-- 手机可见 -->
<div class="container mobile  hidden-lg hidden-md " style=" z-index:2001; position:fixed;bottom:0px; background: #313131;color:white;width:100%;padding:10px;">

<a href="http://wpa.qq.com/msgrd?v=3&amp;uin=195353919&amp;site=qq&amp;menu=yes" target="_black">

<div class="col-xs-4 col-sm-4 text-center" style="background:black;height:40px;padding-top:10px;"><img src="http://www.funboo.cn/statics/images/zhuimeng/lxsj.svg" width="15">QQ联系</div></a>



<a href="http://p.qiao.baidu.com/cps/chat?siteId=10486728&amp;userId=23102115" target="_black">
<div class="col-xs-4 col-sm-4 text-center" style="background:#5bb85d;height:40px;padding-top:10px;">
  <img src="http://www.funboo.cn/statics/images/zhuimeng/jl.svg" width="15">方博互动</div></a>

<a href="http://p.qiao.baidu.com/cps/chat?siteId=10486728&amp;userId=23102115" target="_black">
<div class="col-xs-4 col-sm-4 text-center" style="background:black;height:40px;padding-top:10px;">
  <img src="http://www.funboo.cn/statics/images/zhuimeng/ly.svg" width="15">
  在线咨询</div></a>




</div>
<!-- 手机可见 -->
<!-- 给尾部留空白让底部界面条不会挡住 -->
<footer class="container mobile  hidden-lg hidden-md" style="height: 100px;"></footer>
</body>
</html>