<?php
$z[0]=Array("global","",224,250);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",294,324);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",361,388);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",3617,3642);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channel","\r\n      	<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n      	",3673,3798);
$z[4][4]['type']="top";
$z[4][4]['row']="10";

?>