<?php
$z[0]=Array("global","",277,303);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",352,382);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",424,451);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",552,584);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",662,694);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",774,806);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",882,914);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",987,1019);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",1127,1159);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",1750,1782);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",1887,1919);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("field","(@me==\"\")? @me=\" class='active'\":@me=\"\";",2204,2294);
$z[11][4]['name']="typeid";
$z[11][4]['runphp']="yes";
$z[12]=Array("channel","\r\n					<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n					",2329,2524);
$z[12][4]['type']="top";
$z[12][4]['currentstyle']="<li class='active'><a href='~typelink~' >~typename~</a></li>";

?>