<?php
$z[0]=Array("mda","",30,55);
$z[0][4]['name']="468x60";
$z[1]=Array("global","",113,139);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n				<li><a href='list.php?tid=[field:id/]' [field:rel/]><span>[field:typename/]</span></a>\r\n				</li>",629,893);
$z[2][4]['type']="top";
$z[2][4]['row']="10";
$z[2][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[3]=Array("global","",1008,1033);
$z[3][4]['name']="cfg_cmsurl";

?>