<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("channelartlist","\r\n		<div class=\"swiper-slide\">\r\n			<div class=\"swiper-slide-box\">\r\n			{dede:type}\r\n			<h1>[field:typename/]</h1>\r\n			<h5>[field:description/]</h5>\r\n			{/dede:type}\r\n			<!-- 子栏目 -->\r\n			<ul class=\"list-group\">\r\n				{dede:channel type='son'}\r\n				<li class=\"list-group-item\"><a href='[field:typelink /]'>[field:typename/]</a></li>\r\n				{/dede:channel}\r\n			</ul>\r\n			</div>\r\n		</div>\r\n		",233,678);
$z[1][4]['typeid']="20";
$z[2]=Array("arclist","\r\n\r\n<div   class=\"col-md-3 col-xs-6 col-sm-6 clo-lg-3 indeximg\"><a href='[field:arcurl/]'>[field:image/]</a>\r\n\r\n         <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n             <small style=\"color: #c0c0c0\"><img src=\"/templets/funboo/images/type.png\" style=\"width:11px;\">[field:typelink/]<img src=\"/templets/funboo/images/view.png\" style=\"width:16px;\">[field:click/]hits</small>\r\n\r\n</div>\r\n\r\n",813,1312);
$z[2][4]['typeid']="2";
$z[2][4]['titlelen']="24";
$z[2][4]['imgheight']="90";
$z[2][4]['imgwidth']="112";
$z[2][4]['limit']="0,20";
$z[3]=Array("include","",1330,1367);
$z[3][4]['filename']="footer.htm";

?>