<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\xE2\x80\x9910\xE2\x80\xB2' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (1,11,12,13,14,2,3,5,6,7,8,9,10,15,16) And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,’10′ </font>
Time2017-11-10 15:29:00
*/
?>
<?php  exit();
/*
Page: /plus/list.php?tid=1
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\xE2\x80\x9910\xE2\x80\xB2' at line 6 <br />Error sql: <font color='red'>SELECT arc.*,tp.typedir,tp.typename,tp.corank,tp.isdefault,tp.defaultname,tp.namerule,
        tp.namerule2,tp.ispart,tp.moresite,tp.siteurl,tp.sitepath
        
        FROM `dede_archives` arc LEFT JOIN `dede_arctype` tp on arc.typeid=tp.id
        
         WHERE  arc.typeid IN (1,11,12,13,14,2,3,5,6,7,8,9,10,15,16) And  arc.arcrank > -1    ORDER BY arc.sortrank desc  LIMIT 0,’10′ </font>
Time2017-11-10 15:29:03
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2017-11-23 20:53:14
*/
?>
<?php  exit();
/*
Page: /
Error: No database selected <br />Error sql: <font color='red'>Select * From `dede_homepageset` LIMIT 0,1;</font>
Time2017-11-23 20:53:14
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2017-11-23 20:53:15
*/
?>
<?php  exit();
/*
Page: /
Error: No database selected <br />Error sql: <font color='red'>Select * From `dede_homepageset` LIMIT 0,1;</font>
Time2017-11-23 20:53:15
*/
?>
